name       : python-tornado
version    : 4.5.3
release    : 3
source     :
    - https://github.com/tornadoweb/tornado/archive/v4.5.3.tar.gz : bd2f33a3ede0303d51a424961ee72f8b0a87bcd82ad737d16d8a05364b3d64be
license    : Apache-2.0
component  : programming.python
summary    : Tornado is a Python web framework and asynchronous networking library,
    originally developed at FriendFeed.
description: |
    Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-backports_abc
    - python-certifi
    - python-singledispatch
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
