name       : python-tornado
version    : 6.1.0
release    : 8
source     :
    - https://github.com/tornadoweb/tornado/archive/v6.1.0.tar.gz : 53a4300b786998c516fcacb76a00db6200829bf1d9b8d57e3c150bfd262e2bc8
homepage   : https://www.tornadoweb.org/
license    : Apache-2.0
component  : programming.python
summary    : Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed
description: |
    Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test -m tornado.test.runtests --verbose
