name       : python-tornado
version    : 5.0.0
release    : 4
source     :
    - https://github.com/tornadoweb/tornado/archive/v5.0.0.tar.gz : 7e54aa2bf2799c559b3e05d314c88b335e78d1420b072071f8b63af6bb50d714
license    : Apache-2.0
component  : programming.python
summary    : Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
description: |
    Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-backports_abc
    - python-futures
    - python-singledispatch
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
