name       : python-tornado
version    : 6.2.0
release    : 10
source     :
    - https://github.com/tornadoweb/tornado/archive/refs/tags/v6.2.0.tar.gz : c2e902e4771eb90b057c7629fa239a59ecae63052919c3b5e61253f2c8a5f0d6
homepage   : https://www.tornadoweb.org/
license    : Apache-2.0
component  : programming.python
summary    : Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed
description: |
    Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed. By using non-blocking network I/O, Tornado can scale to tens of thousands of open connections, making it ideal for long polling, WebSockets, and other applications that require a long-lived connection to each user.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # https://github.com/tornadoweb/tornado/issues/2947
#    %python3_test -m tornado.test.runtests --verbose
