name       : python-tornado
version    : 5.1.1
release    : 7
source     :
    - https://github.com/tornadoweb/tornado/archive/v5.1.1.tar.gz : a1da335a2978b9a8c3544cab10076d799442d7988ed0b4f2be035fe4388ca8dd
license    : Apache-2.0
component  : programming.python
summary    : Tornado is a Python web framework and asynchronous networking library,
    originally developed at FriendFeed.
description: |
    Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-backports_abc
    - python-futures
    - python-singledispatch
rundeps    :
    - python-backports_abc
    - python-futures
    - python-singledispatch
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test -m tornado.test.runtests --verbose
    # Fails on 3.9
    #python3_test -m tornado.test.runtests --verbose
