name       : python-tornado
version    : 4.5.2
release    : 1
source     :
    - https://github.com/tornadoweb/tornado/archive/v4.5.2.tar.gz : f30c723827afd2f8aceae2a13a40ee05487268920fd55cf3b5b33f02bd15511e
license    : Apache-2.0
component  : programming.python
summary    : Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
description: |
    Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-backports_abc
    - python-certifi
    - python-singledispatch
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
